cask_args appdir: "/Applications"

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tab "homebrew/cask-fonts"

brew "anyenv"
brew "exa"
brew "git"
brew "git-secrets"
brew "jq"
brew "tree"
brew "wget"
brew "starship"
brew "font-hackgen-nerd"
brew "font-hackgen"

cask "appcleaner"
cask "aws-vault"
cask "cheatsheet"
cask "clipy"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "keyboardcleantool"
cask "notion"
cask "postman"
cask "simplenote"
cask "slack"
cask "sourcetree"
cask "the-unarchiver"
cask "visual-studio-code"
cask "font-ricty-diminished"
cask 